name: Deploy to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  deploy-to-hub:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          lfs: true

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          pip install huggingface_hub scikit-learn joblib numpy

      # Étape 4 : Préparer les fichiers de déploiement
      - name: Prepare deployment folder
        run: |
          mkdir hf_deployment
          python script_python.py
          cp script_python.py hf_deployment/
          cp simple_model.joblib hf_deployment/
          cp README.md hf_deployment/
          echo "Contenu du dossier de déploiement :"
          ls -l hf_deployment

      # Étape 5 : Déployer sur Hugging Face via script Python
      - name: Deploy to Hugging Face via script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python deploy_to_huggingface.py

  send-notification:
    if: success()
    needs: deploy-to-hub
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "✅ Déploiement Réussi : ${{ github.repository }}"
          to: ${{ secrets.MAIL_USERNAME }}
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            Bonjour,

            Le déploiement du modèle vers Hugging Face Hub est terminé avec succès.

            ✅ Repo : ${{ github.repository }}
            🔁 Commit : ${{ github.sha }}
            🔗 Modèle en ligne : https://huggingface.co/Hiroshi99/Model_SN_GitHub

            Bien cordialement,
            Votre pipeline GitHub Actions.